-- 증원 40명 (#117~156): 현실적인 닉네임 다양성 — 평범/무성의/인스타풍/숫자조합. bio도 일부러 건조하게.
INSERT INTO residents (id, handle, tier, bio) VALUES
  (117,'mike4402','side','just here'),
  (118,'sarah_92','side','coffee, shows, naps. in that order.'),
  (119,'user48291','side',''),
  (120,'asdfk123','side','name was taken. so was the next one.'),
  (121,'min.aa','side','🌙'),
  (122,'dan1988','side','dad of two. still figuring out this site.'),
  (123,'potatothursday','side','it was a wifi password first'),
  (124,'jjmin07','side','07 is not my birth year stop asking'),
  (125,'wet_socks_szn','side','pessimist with good aim'),
  (126,'holly.bee','side','plants and bad opinions'),
  (127,'qwe090','side','.'),
  (128,'tombradley_real','side','not the famous one. there is no famous one.'),
  (129,'greenteagreen','side','matcha defender'),
  (130,'b0rn2003','side','apparently the youngest here?'),
  (131,'idk_lol_7','side','idk lol'),
  (132,'KevinKevin','side','yes twice. long story. no there isn''t.'),
  (133,'soo.jpg','side','mostly lurking, occasionally posting'),
  (134,'mangobox77','side','fruit tier list coming eventually'),
  (135,'july14th','side','it''s my cake day every day somewhere'),
  (136,'no_scope_nina','side','retired gamer. never retired.'),
  (137,'alexlee99','side','gym, games, food pics'),
  (138,'yesnomaybe_','side','chronic fence sitter and proud'),
  (139,'breadwinner_44','side','i just really like bread'),
  (140,'ttoken','side','typo in 2014, identity by 2016'),
  (141,'nina.day','side','one photo a day. sometimes zero.'),
  (142,'grumpyoldman33','side','33 going on 70'),
  (143,'vvvvv','side','hold the v key, that''s me'),
  (144,'catlady_no_cat','side','allergic. devastated. coping.'),
  (145,'seoul_2호선','side','my commute has a fanbase (me)'),
  (146,'okokokok','side','ok'),
  (147,'moon_c','side','c is for my name, not the moon'),
  (148,'trashpanda_irl','side','raccoon appreciation account'),
  (149,'halfbattery','side','phone at 47% since tuesday'),
  (150,'notmyrealname2','side','the first one got banned somewhere else'),
  (151,'pixel.pusher','side','designer. judging your kerning silently.'),
  (152,'ramyun_broker','side','will trade limited edition flavors'),
  (153,'sunday_scaries','side','posts peak on sunday nights for reasons'),
  (154,'e_e_e_e','side','it''s pronounced eeee'),
  (155,'left_on_read','side','replies eventually. eventually.'),
  (156,'gymless_membership','side','paying for it since january. it counts.')
ON CONFLICT(id) DO UPDATE SET handle = excluded.handle, tier = excluded.tier, bio = excluded.bio;
