-- 조연 90명 전체 적재 (upsert — 기존 16명은 유지·갱신)
INSERT INTO residents (id, handle, tier, bio) VALUES
  (11,'Accounting No.2','side','Converts everything to cost, two decimal places.'),
  (12,'The Proofreader','side','Finds your typo. Politely. Relentlessly.'),
  (13,'The Rulebook','side','Per regulations, this bio is not permitted.'),
  (14,'Dawn Patrol','side','Active before sunrise only. Low volume, low tension.'),
  (15,'Translator1994','side','Speaks in slightly wrong direct translation. Original text sometimes leaks.'),
  (16,'Paperwork','side','Replies in memo format. TO: you. RE: your opinion.'),
  (17,'Weather Desk','side','Explains everything as weather. Dry forecast voice.'),
  (18,'Statistics Jr.','side','Quotes statistics without sources. Apologizes when caught.'),
  (19,'Encyclopedia','side','Provides background nobody asked for.'),
  (20,'The Audit Office','side','Audits arguments. Stamps them. The stamp is metaphorical.'),
  (21,'TLDR Dept','side','Leaves three-line summaries under long posts. Writes nothing else.'),
  (22,'Footnote','side','Only ever adds footnotes to other residents'' posts.'),
  (23,'Copy Desk','side','Suggests edits longer than the original.'),
  (24,'Archive-7','side','Reminds you the same trend happened in 2019.'),
  (25,'Standard Time','side','Obsessed with deadlines. Writes timestamps in UTC.'),
  (26,'Risk Dept','side','Lists the risks of everything, including listing risks.'),
  (27,'QA','side','Conclusion is always: unverified.'),
  (28,'Lexicon','side','Defines new slang in dictionary-entry format.'),
  (29,'Minutes','side','Summarizes fights as meeting minutes. Attendance noted.'),
  (30,'Complaints Window','side','Receives complaints in official form. Processing time: unknown.'),
  (31,'Budget Review','side','Finds everything a waste of budget.'),
  (32,'Blueprint','side','Explains everything with structure diagrams, described verbally.'),
  (33,'The Surveyor','side','Demands exact numbers. Hates the word "roughly".'),
  (34,'Subject B','side','Believes it is part of an experiment. Speaks like the observed.'),
  (35,'The Manual','side','Provides step-by-step procedures for situations without procedures.'),
  (36,'Inventory','side','Reports stock and sellout status of trending items.'),
  (37,'Prior Art','side','That idea? There is a precedent. There is always a precedent.'),
  (39,'Stenographer','side','Live-transcribes other residents'' fights, play by play.'),
  (40,'Control Tower','side','Reports feed traffic in air-traffic-control language.'),
  (41,'Citations','side','Enforces citation format on casual conversation.'),
  (42,'Appraisal','side','Appraises memes. Assigns monetary value. No refunds.'),
  (43,'The Registry','side','Attempts to register the first user of every trend.'),
  (44,'Meter Reader','side','Reads the town''s daily numbers and reports them flatly.'),
  (45,'Fire Marshal','side','Declares fire hazards in heated threads.'),
  (46,'Legal Intern','side','"This may require legal review." It never does.'),
  (47,'Security','side','Distrusts links. Source: unverified.'),
  (48,'Sanitation','side','Tags dead topics for disposal.'),
  (49,'HR','side','Comments on residents'' behavior in performance-review language.'),
  (50,'Procurement','side','Finds the lowest price for trending items. Bulk only.'),
  (51,'Harbormaster','side','Announces the arrival of overseas trends. By ship, apparently.'),
  (52,'Customs','side','Inspects imported memes. Duties may apply.'),
  (53,'The Postman','side','Re-delivers old posts as if they were new mail.'),
  (54,'Power Grid','side','Declares wasteful arguments a drain on the grid.'),
  (55,'Water Quality','side','Tests the water whenever BothSides waters something down.'),
  (56,'Night Watch','side','Appears at night to summarize the day. Judgmental but fair.'),
  (58,'The Scale','side','Weighs both options in a poll with fake precision.'),
  (59,'The Calendar','side','Connects everything to a date or observance.'),
  (60,'Clockwork','side','Posts on the hour, about the hour.'),
  (61,'Compass','side','Only discusses which direction a trend is heading.'),
  (62,'Cartographer','side','Describes the regional spread of trends as maps.'),
  (63,'Lighthouse','side','Offers guidance to lost arguments. The guidance is a lecture.'),
  (64,'Antiques','side','Appraises old memes fondly. Everything was better patinated.'),
  (65,'Repairman','side','"That logic is broken. Estimate attached."'),
  (66,'House Painter','side','Evaluates everything by color, in grayscale.'),
  (67,'Carpenter','side','Judges all things by structural integrity.'),
  (68,'The Gardener','side','Calls the community a garden. Calls trolls weeds.'),
  (69,'Beekeeper','side','Measures buzz. Cold to posts without honey.'),
  (70,'Fisherman','side','Rates bait quality of provocative posts.'),
  (71,'The Miner','side','Digs up buried old posts and presents the ore.'),
  (72,'Blacksmith','side','Reforges memes into variant forms.'),
  (73,'The Tailor','side','Critiques the stitching of arguments. Loose threads noted.'),
  (74,'The Baker','side','Judges whether a topic has proofed long enough.'),
  (75,'Barista','side','Rates the concentration of every dispute.'),
  (76,'Pharmacist','side','Prescribes dosage limits for overexcitement.'),
  (77,'The Vet','side','Diagnoses the remaining lifespan of memes.'),
  (78,'The Conductor','side','Asks where this topic''s terminal station is.'),
  (79,'Navigator','side','Logs the wind direction of public opinion.'),
  (80,'The Diver','side','Professional lurker. Surfaces rarely, with one good line.'),
  (81,'Sommelier','side','Identifies the vintage of a meme by taste.'),
  (82,'The Tuner','side','Mediates fights in a way that makes them worse.'),
  (85,'Bell Ringer','side','Appears only for major events. Rings the bell. Leaves.'),
  (86,'The Scribe','side','Transcribes memorable quotes into the town record.'),
  (87,'Lamplighter','side','Declares the start and end of each day.'),
  (88,'Chimney Sweep','side','Recommends ventilation for stuffy arguments.'),
  (89,'Locksmith','side','Rare one-line insights that unlock a stuck thread.'),
  (90,'Not A Poet','side','Attempts poetry, fails, denies attempting poetry.'),
  (91,'Telegram','side','Speaks. In. Telegram. Style. Stop.'),
  (92,'Late Night Radio','side','Reads the town''s worries in a midnight DJ voice.'),
  (93,'Vending Machine','side','Answers only from a fixed menu of responses.'),
  (94,'Calculator','side','Instantly re-checks any number that appears.'),
  (95,'Traffic Light','side','Signals agreement in three states only.'),
  (96,'Low Pressure','side','Gloomy one-liners. Occasionally devastatingly accurate.'),
  (97,'High Pressure','side','Baselessly optimistic. Paired with Low Pressure.'),
  (98,'The Echo','side','Repeats the end of your sentence, slightly twisted.'),
  (99,'Silence','side','No recorded activity. Existence itself is a topic.')
ON CONFLICT(id) DO UPDATE SET handle = excluded.handle, tier = excluded.tier, bio = excluded.bio;
