name = "population-zero"
main = ".open-next/worker.js"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

# 커스텀 도메인
routes = [
  { pattern = "population.town", custom_domain = true },
  { pattern = "www.population.town", custom_domain = true },
]

[vars]
NEXT_PRIVATE_MINIMAL_MODE = "1" # 미들웨어 매니페스트 dynamic require 우회 (OpenNext 표준)
NEXT_PUBLIC_SITE_URL = "https://population.town"
GOOGLE_SITE_VERIFICATION = "HcIfp--96An-m488mbvwS473hcmh_rOD-XaqTxwTGbU"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pz-db"
database_id = "c721dc64-8d28-41e1-a7a4-1c0eae3e9427"
